### ISSUE TITLE
Unable to get prisma 5 with nixpacks openssl

### ISSUE THREAD

**Issue by Maxim-Filimonov** [railwayapp/nixpacks#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following up on [the issue](https://github.com/railwayapp/nixpacks/issues/574) Prisma does support open ssl 3.0.x now.
However, for some reason I'm still not able to use nixpack with Prisma.
I tried installing `libssl-dev` in setup stage and got the same error. 

### To reproduce

After building i get the following error on trying to instantiate `PrismaClient()`
```
PrismaClientInitializationError: Unable to require(`/app/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node`).

Prisma cannot find the required `libssl` system library in your system. Please install openssl-3.0.x and try again.

Details: libssl.so.3: cannot open shared object file: No such file or directory

at new e (/app/node_modules/@prisma/client/runtime/library.js:26:1871)
```

### Expected behavior

Able to build and deploy application using Prisma.

### Environment

nixpacks.toml
```
[phases.setup]
aptPkgs = ["..."]
[phases.build]
cmds = ["...", "bunx prisma generate", "bunx prisma migrate deploy"]
```
package.json
```
 "dependencies": {
    "@prisma/client": "5.7.0",
  },
```
**Bun:** 1.0.17

I have no problems running locally.

**Comment by coffee-cup** [comment]
We have an example that builds and runs no problem using Prisma 5 and bun https://github.com/railwayapp/nixpacks/tree/main/examples/node-bun-prisma.

I can check this out further, but there is evidence of both working so I am not sure what is going on with your specific repo. Do you have a sample repo that doesn't work with Bun?

**Comment by Maxim-Filimonov** [comment]
@coffee-cup I tried using linked example and it fails with different error for some reason. 
```


$ bunx prisma migrate deploy

Prisma schema loaded from prisma/schema.prisma

Datasource "db": PostgreSQL database "railway", schema "public" at "roundhouse.proxy.rlwy.net:17360"

Error: P1001: Can't reach database server at `roundhouse.proxy.rlwy.net`:`17360`

Please make sure your database server is running at `roundhouse.proxy.rlwy.net`:`17360`.

error: script "start" exited with code 1 (SIGHUP)

$ bunx prisma migrate deploy
```
I did add shared variable DATABASE_URL.
Project on railway -> https://railway.app/project/f43b6f45-bce0-4138-bb1f-4dedca53ed97
Tried recreating postgres service - no luck.

**Comment by thomas779** [comment]
Bumping this as I'm getting the exact issue to @Maxim-Filimonov. 

1. fork this repo: https://github.com/amorriscode/elysia-starter
2. `"prisma": "5.7.1"` and `"@prisma/client": "5.7.1"`
3. cp this `schema.prisma`:

What's your Prisma schema set-up Maxim ? 
This is mine:
```prisma
datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

generator client {
    provider      = "prisma-client-js"
    output        = "./generated/client"
    binaryTargets = ["native", "linux-musl", "debian-openssl-3.0.x"]
}
```

`nixpacks.toml`:
```toml
[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bunx prisma generate', 
        'bunx prisma migrate deploy', 
        'bun build --target=bun ./src/index.ts --outdir ./build']

[start]
cmd = 'bun run src/index.ts'
```

Error:
```bash
PrismaClientInitializationError: Unable to require(`/app/prisma/generated/client/libquery_engine-debian-openssl-3.0.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-3.0.x and try again.
Details: libssl.so.3: cannot open shared object file: No such file or directory
```

Tried to add `'openssl_3_0_x` to my `nixPkgs = ['bun', 'openssl_3_0_x']` but that didn't work.

**Comment by imadbz** [comment]
+1 couldn't get it to work either

**Comment by baptisteArno** [comment]
I have the exact same error when trying to deploy an Elysia app. Has anyone found a fix?

**Comment by Maxim-Filimonov** [comment]
My fix was to migration to fly.io :|

**Comment by iloveitaly** [comment]
`--libs openssl` will fix the issue, or we can get this PR merged :) 

https://github.com/railwayapp/nixpacks/pull/1054

**Comment by Maxim-Filimonov** [comment]
@iloveitaly where to add `--libs openssl` ?

**Comment by baptisteArno** [comment]
@iloveitaly Nah, I that's not it... I think nixpacks even detected that it needs openssl by default for my project.

Still, I tried to specifically tell it to add the openssl lib with the env `NIXPACKS_PKGS=openssl`

```
╔═══════════════ Nixpacks v1.20.0 ══════════════╗
║ setup │ openssl, nodejs_18, bun, openssl ║
║───────────────────────────────────────────────║
║ install │ bun install ║
║───────────────────────────────────────────────║
║ build │ bun build:chat-api ║
║───────────────────────────────────────────────║
║ start │ bun start:chat-api ║
╚═══════════════════════════════════════════════╝
```

The problem happens at runtime, on the docker when the app is running, on Prisma init, it says:

```
PrismaClientInitializationError: Unable to require(`/app/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node`).

Prisma cannot find the required `libssl` system library in your system. Please install openssl-3.0.x and try again.

Details: libssl.so.3: cannot open shared object file: No such file or directory

at new e (/app/node_modules/@prisma/client/runtime/library.js:26:1871)
```

**Comment by iloveitaly** [comment]
You need it as a lib, not as a package. Without this the ENV config is not changed. Take a look at the linked PR: https://github.com/railwayapp/nixpacks/pull/1054

**Comment by ksaitor** [comment]
Even on the latest `prisma@^5.11.0` still getting this error on Nixpacks. 

```
╔═════════════ Nixpacks v1.21.2 ═════════════╗
║ setup │ nodejs_21, bun, openssl ║
║────────────────────────────────────────────║
║ install │ bun i --no-save ║
║────────────────────────────────────────────║
║ build │ echo Skip build process ║
║────────────────────────────────────────────║
║ start │ bun run worker/main.worker.ts ║
╚════════════════════════════════════════════╝
```

**Comment by ksaitor** [comment]
> --libs openssl

where do you add `--libs openssl` ? @iloveitaly

**Comment by Maxim-Filimonov** [comment]
@ksaitor I haven't tried since it wasn't working when I needed it for initial launch. It works pretty well on fly I don't really see a reason why try to move it back to railway TBH.

**Comment by JakeCooper** [comment]
Fixable by simply specifying binaryTargets

https://github.com/amorriscode/elysia-starter/issues/2#issuecomment-2019438468

**Comment by ksaitor** [comment]
added `NIXPACKS_LIBS=openssl` and it worked!
notice: **not** `NIXPACKS_PKGS`

cc @baptisteArno check it out

**Comment by JakeCooper** [comment]
@ksaitor Could you link the Railway project where it works or a repo with it working so that we can fix it at the nixpacks level?

**Comment by ksaitor** [comment]
> @ksaitor Could you link the Railway project where it works or a repo with it working so that we can fix it at the nixpacks level?

@JakeCooper I'm not on Railway. I'm on Coolify, that's using Nixpacks under the hood. Nixpacks v1.21.2.

**Comment by nicnocquee** [comment]
@ksaitor where in coolify did you add `NIXPACKS_LIBS=openssl`? I try to do prisma migration before the build but it cannot reach the database no matter what.

**Comment by ksaitor** [comment]
> @ksaitor where in coolify did you add `NIXPACKS_LIBS=openssl`? I try to do prisma migration before the build but it cannot reach the database no matter what.

Go to your project > Configuration > Environment Variables

And, perhaps try checking "Build Variable".

I'm not running prisma migrations during build in my app. So i can't comment more here unfortunately.


![Screenshot 2024-06-16 at 14 00 02](https://github.com/railwayapp/nixpacks/assets/936436/0ccefa85-7b2a-47fe-ad4f-eda1e7bf1fac)

**Comment by iloveitaly** [comment]
👋 Hey All! I'm helping with maintenance on nixpacks/railpack. We are putting most of our development effort behind railpack at this point, which is why this issue hasn't gotten a lot of love. I _think_ automated dependency installation for prisma [should be working](https://github.com/railwayapp/railpack/tree/main/examples/node-prisma) on railpack.

I couldn't get this working on nixpacks and ended up using a [custom dockerfile](https://github.com/ryanstout/question_to_sql/blob/be6b7fb17f875d5f029d1ec06114312c3c4feaa7/docker/shared.sh#L23C3-L23C26).

Could you try building your project with railpack and let me know if you run into any trouble?

One of our goals with railpack is feature compatibility with nixpacks and easy migration from it. Let me know if you run into any trouble switching over.

**Comment by thomas779** [comment]
UPDATE!

I got this working with a custom Dockerfile. This is my config in case it helps anyone here. Thanks @iloveitaly 🥇 

```Dockerfile
# Use Ubuntu 22.04 as base image for OpenSSL 3.0 compatibility
FROM ubuntu:22.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    openssl \
    ca-certificates \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Node.js 22
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy source code
COPY . .

# Generate Prisma client
RUN bun run db:generate

# Build the application
RUN bun run build

# Expose port
EXPOSE 3000

# Start command with database deployment
CMD ["sh", "-c", "bun run db:deploy && bun run start"]
```

```prisma
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native", "linux-musl", "debian-openssl-3.0.x"]
  previewFeatures = ["postgresqlExtensions"]
}

datasource db {
  provider   = "postgresql"
  url        = env("DATABASE_URL")
  extensions = [citext]
}
```
```json
{
  "$schema": "https://railway.com/railway.schema.json",
  "build": {
    "builder": "DOCKERFILE"
  }
}
```
