### ISSUE TITLE
Numpy C extensions are not found

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#304]
The `numpy` package fails to import the required C-extensions.

Example

![image](https://user-images.githubusercontent.com/3044853/178786995-e5b12007-68a8-40e4-9aee-8e3583936dbb.png)

Fails on startup with

![image](https://user-images.githubusercontent.com/3044853/178787047-7dced85d-b2ed-490c-862a-d51ef433865d.png)

### Code

main.py
```py
import numpy as np

print("Started")
print(np)
```

requirements.txt
```
numpy==1.23.1
```

Error

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/opt/venv/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/opt/venv/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libz.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import numpy as np
  File "/opt/venv/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/venv/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/opt/venv/bin/python"
  * The NumPy version is: "1.23.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libz.so.1: cannot open shared object file: No such file or directory
```

**Comment by aarnphm** [comment]
I believe this has been fixed?

**Comment by coffee-cup** [comment]
Yup!
