### ISSUE TITLE
Trouble Deploying Django App That Uses An External SQl Database

### ISSUE THREAD

**Issue by MCole-K9** [railwayapp/nixpacks#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

build fails while trying to deploy my Django application. 

For context: I'm using planetscale for the mysql database and I use pipenv to create my virtual environment locally

Here is the build log:

``` 
#10 [stage-0 6/8] COPY . /app/
#10 sha256:45b179abd76949bbb9d7e4b3059bbac293597b647224e6037f1f5470615c9ec3
 
#10 DONE 0.1s
 
#11 [stage-0 7/8] RUN --mount=type=cache,id=s/7cba9214-d460-4f63-9dab-0761a89e5b3e-/root/cache/pip,target=/root/.cache/pip python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt
#11 sha256:f7747eb633f7186c74c5beea6c467701fbdad7ca6a1b416fb1e863f8af1e2620
 
#11 5.507 Collecting asgiref==3.5.2
 
#11 5.511   Using cached asgiref-3.5.2-py3-none-any.whl (22 kB)
 
#11 5.716 Collecting Django==4.1
#11 5.772   Using cached Django-4.1-py3-none-any.whl (8.1 MB)
 
#11 5.909 Collecting django-environ==0.9.0
 
#11 5.913   Using cached django_environ-0.9.0-py2.py3-none-any.whl (17 kB)
#11 5.949 Collecting django-psdb-engine==1.0.6
#11 5.952   Using cached django_psdb_engine-1.0.6-py2.py3-none-any.whl (3.7 kB)
#11 6.009 Collecting gunicorn==20.1.0
#11 6.014   Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
 
#11 6.073 Collecting mysqlclient==2.1.1
#11 6.077   Using cached mysqlclient-2.1.1.tar.gz (88 kB)
#11 6.100   Preparing metadata (setup.py): started
 
#11 6.325   Preparing metadata (setup.py): finished with status 'error'
#11 6.337   error: subprocess-exited-with-error
#11 6.337
#11 6.337   × python setup.py egg_info did not run successfully.
#11 6.337   │ exit code: 1
#11 6.337   ╰─> [16 lines of output]
#11 6.337       /nix/store/3j918i1nbwhby0y38bn2r438rjhh8f4d-bash-5.1-p16/bin/sh: line 1: mysql_config: command not found
#11 6.337       /nix/store/3j918i1nbwhby0y38bn2r438rjhh8f4d-bash-5.1-p16/bin/sh: line 1: mariadb_config: command not found
#11 6.337       /nix/store/3j918i1nbwhby0y38bn2r438rjhh8f4d-bash-5.1-p16/bin/sh: line 1: mysql_config: command not found
#11 6.337       Traceback (most recent call last):
#11 6.337         File "<string>", line 2, in <module>
#11 6.337         File "<pip-setuptools-caller>", line 34, in <module>
#11 6.337         File "/tmp/pip-install-7lrggvk7/mysqlclient_fa8e665c60084414b59c07d8ff8b968c/setup.py", line 15, in <module>
#11 6.337           metadata, options = get_config()
#11 6.337         File "/tmp/pip-install-7lrggvk7/mysqlclient_fa8e665c60084414b59c07d8ff8b968c/setup_posix.py", line 70, in get_config
#11 6.337           libs = mysql_config("libs")
#11 6.337         File "/tmp/pip-install-7lrggvk7/mysqlclient_fa8e665c60084414b59c07d8ff8b968c/setup_posix.py", line 31, in mysql_config
#11 6.337           raise OSError("{} not found".format(_mysql_config_path))
 
#11 6.337       OSError: mysql_config not found
#11 6.337       mysql_config --version
#11 6.337       mariadb_config --version
#11 6.337       mysql_config --libs
#11 6.337       [end of output]
#11 6.337
#11 6.337   note: This error originates from a subprocess, and is likely not a problem with pip.
#11 6.341 error: metadata-generation-failed
#11 6.341
#11 6.341 × Encountered error while generating package metadata.
#11 6.341 ╰─> See above for output.
#11 6.341
#11 6.341 note: This is an issue with the package mentioned above, not pip.
#11 6.341 hint: See above for details.
#11 6.348 WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
#11 6.348 You should consider upgrading via the '/opt/venv/bin/python -m pip install --upgrade pip' command.
 
#11 ERROR: executor failed running [/bin/bash -ol pipefail -c python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt]: exit code: 1
 
-----
> [stage-0 7/8] RUN --mount=type=cache,id=s/7cba9214-d460-4f63-9dab-0761a89e5b3e-/root/cache/pip,target=/root/.cache/pip python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt:
-----
 
executor failed running [/bin/bash -ol pipefail -c python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt]: exit code: 1
 
Error: Docker build failed
```

### To reproduce

1. Fork this repository - https://github.com/MCole-K9/Django-Railway 
2. Create a database on planetscale 
3. Set the environment variables to match those in settings.py
4. Deploy from repo on railway

### Environment

Windows 10 - local

**Comment by prakhar1144** [comment]
**I'm still facing the issue.**


I am trying to deploy : https://github.com/prakhar1144/Carpool-Backend
It was working fine on Heroku, I'm migrating it to railway.

Here's is the build log:

```
==============
Using Nixpacks
==============
context: 549049020551af1cfb662312f37b94e3
 
╔═══════════════════════════════ Nixpacks v1.1.1 ══════════════════════════════╗
║ setup      │ python38, postgresql, gcc                                       ║
║──────────────────────────────────────────────────────────────────────────────║
║ install    │ python -m venv /opt/venv && . /opt/venv/bin/activate && pip     ║
║            │ install -r requirements.txt                                     ║
║──────────────────────────────────────────────────────────────────────────────║
║ start      │ daphne Carpool.asgi:application --port $PORT --bind 0.0.0.0 -v2 ║
╚══════════════════════════════════════════════════════════════════════════════╝
 
 
#2 [internal] load .dockerignore
 
#2 sha256:42f8e8e831583a26b20534d8cc09cee56e7efa0b0d573252adc21bfc3bdca7d2
 
#2 transferring context:
 
#2 transferring context: 2B done
 
#2 ...
 
#1 [internal] load build definition from Dockerfile
#1 sha256:157d769f1798c2f213524ddeea6d5045f689b818e749a33cff1eb11c6129b1e7
#1 transferring dockerfile: 1.87kB done
#1 DONE 0.7s
 
 
#2 [internal] load .dockerignore
#2 sha256:42f8e8e831583a26b20534d8cc09cee56e7efa0b0d573252adc21bfc3bdca7d2
#2 DONE 1.0s
 
 
#3 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1673375667
#3 sha256:d1b589dc22aa3588cda5918cc7d2de8fbc9cb1b6b86f0173223491302aa8c821
 
#3 DONE 0.6s
 
#4 [stage-0 1/8] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1673375667@sha256:528931c0e3ba98f759dc91b36522b8c1743ad85152447d282b427d5f04914af7
#4 sha256:45b8a7aac880bd83a4a72f1829fc36d831784fd9888bfa84a29f6718b1baf49d
#4 DONE 0.0s
 
#6 [internal] load build context
#6 sha256:e16626e6c0dbf9fc9f699f0048ff91eff45d9f895e6454d287367e17b5dbad9f
 
#6 transferring context: 37.95kB done
 
#6 DONE 0.4s
 
#5 [stage-0 2/8] WORKDIR /app/
#5 sha256:bbd825bd1b472a0ab5d7ac76fbd4e9a78b084f218bdd438e040e31b97130ffde
#5 CACHED
 
#7 [stage-0 3/8] COPY .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix
#7 sha256:86a37a9b1191b6b152b5a643047a3de71ae791bc78d22c51a3b2d016e426468f
#7 CACHED
 
#8 [stage-0 4/8] RUN nix-env -if .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix && nix-collect-garbage -d
#8 sha256:8d20da43ab826ce8a16383af61369093f183826de3207e834432f1da80b41685
#8 CACHED
 
#9 [stage-0 5/8] RUN printf '\nPATH=/opt/venv/bin:$PATH' >> /root/.profile
#9 sha256:66fa2612d0ccdc1c984dfabfde589f3ec04c0fbd230cde2147a6a3421ce011ee
 
#9 DONE 1.3s
 
 
#10 [stage-0 6/8] COPY . /app/.
#10 sha256:7c7fb94f7676c155fcf000e67f1c6f614c3483296ff237ff3de17b587164dd81
 
#10 DONE 1.0s
 
 
#11 9.639 Collecting hiredis==2.0.0
#11 9.649   Downloading hiredis-2.0.0-cp38-cp38-manylinux2010_x86_64.whl (85 kB)
#11 9.679      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 KB 2.8 MB/s eta 0:00:00
#11 9.727 Collecting hyperlink==21.0.0
 
#11 9.737   Downloading hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
#11 9.766      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.6/74.6 KB 2.5 MB/s eta 0:00:00
#11 9.821 Collecting idna==3.3
#11 9.838   Downloading idna-3.3-py3-none-any.whl (61 kB)
 
#11 9.869      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 1.9 MB/s eta 0:00:00
#11 9.921 Collecting incremental==21.3.0
#11 9.933   Downloading incremental-21.3.0-py2.py3-none-any.whl (15 kB)
 
#11 10.04 Collecting inflection==0.5.1
#11 10.05   Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
 
#11 10.16 Collecting jsonschema==4.0.1
#11 10.17   Downloading jsonschema-4.0.1-py3-none-any.whl (69 kB)
#11 10.20      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 KB 2.3 MB/s eta 0:00:00
 
#11 10.35 Collecting msgpack==1.0.2
#11 10.36   Downloading msgpack-1.0.2-cp38-cp38-manylinux1_x86_64.whl (302 kB)
#11 10.39      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.8/302.8 KB 10.8 MB/s eta 0:00:00
 
#11 10.46 Collecting mysqlclient==2.0.3
#11 10.47   Downloading mysqlclient-2.0.3.tar.gz (88 kB)
#11 10.50      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.9/88.9 KB 3.0 MB/s eta 0:00:00
 
#11 10.52   Preparing metadata (setup.py): started
 
#11 10.70   Preparing metadata (setup.py): finished with status 'error'
#11 10.71   error: subprocess-exited-with-error
#11 10.71
#11 10.71   × python setup.py egg_info did not run successfully.
#11 10.71   │ exit code: 1
#11 10.71   ╰─> [16 lines of output]
#11 10.71       mysql_config --version
#11 10.71       /nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16/bin/sh: line 1: mysql_config: command not found
#11 10.71       mariadb_config --version
#11 10.71       /nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16/bin/sh: line 1: mariadb_config: command not found
#11 10.71       mysql_config --libs
#11 10.71       /nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16/bin/sh: line 1: mysql_config: command not found
#11 10.71       Traceback (most recent call last):
#11 10.71         File "<string>", line 2, in <module>
#11 10.71         File "<pip-setuptools-caller>", line 34, in <module>
#11 10.71         File "/tmp/pip-install-waf9qk_i/mysqlclient_d17c4403e9a84110b7fbebd20a958b63/setup.py", line 15, in <module>
#11 10.71           metadata, options = get_config()
#11 10.71         File "/tmp/pip-install-waf9qk_i/mysqlclient_d17c4403e9a84110b7fbebd20a958b63/setup_posix.py", line 70, in get_config
#11 10.71           libs = mysql_config("libs")
#11 10.71         File "/tmp/pip-install-waf9qk_i/mysqlclient_d17c4403e9a84110b7fbebd20a958b63/setup_posix.py", line 31, in mysql_config
#11 10.71           raise OSError("{} not found".format(_mysql_config_path))
#11 10.71       OSError: mysql_config not found
#11 10.71       [end of output]
#11 10.71
#11 10.71   note: This error originates from a subprocess, and is likely not a problem with pip.
#11 10.71 error: metadata-generation-failed
#11 10.71
#11 10.71 × Encountered error while generating package metadata.
#11 10.71 ╰─> See above for output.
#11 10.71
#11 10.71 note: This is an issue with the package mentioned above, not pip.
#11 10.71 hint: See above for details.
 
#11 10.91 WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
#11 10.91 You should consider upgrading via the '/opt/venv/bin/python -m pip install --upgrade pip' command.
 
#11 ERROR: executor failed running [/bin/bash -ol pipefail -c python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt]: exit code: 1
-----
> [stage-0 7/8] RUN --mount=type=cache,id=s/4f956cd7-f561-4269-8e27-5fc2b2b49197-/root/cache/pip,target=/root/.cache/pip python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt:
-----
executor failed running [/bin/bash -ol pipefail -c python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt]: exit code: 1
 
Error: Docker build failed
 
```
