### ISSUE TITLE
Build fails as nixpacks ignores readme file

### ISSUE THREAD

**Issue by frafra** [railwayapp/nixpacks#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
$ rootlesskit nixpacks build . --name pyfilesystem-sync

╔═══════════════════════════════ Nixpacks v0.4.1 ══════════════════════════════╗
║ Setup      │ python38, gcc                                                   ║
║──────────────────────────────────────────────────────────────────────────────║
║ Install    │ python -m venv /opt/venv && . /opt/venv/bin/activate && pip     ║
║            │ install --upgrade build setuptools && pip install .             ║
║──────────────────────────────────────────────────────────────────────────────║
║ Build      │                                                                 ║
║──────────────────────────────────────────────────────────────────────────────║
║ Start      │ python -m pyfilesystem-sync                                     ║
╚══════════════════════════════════════════════════════════════════════════════╝

[+] Building 39.3s (11/12)                                                                           
 => [internal] load build definition from Dockerfile                                            0.0s
 => => transferring dockerfile: 794B                                                            0.0s
 => [internal] load .dockerignore                                                               0.0s
 => => transferring context: 2B                                                                 0.0s
 => [internal] load metadata for ghcr.io/railwayapp/nixpacks:debian-1662422726                  1.6s
 => [stage-0 1/8] FROM ghcr.io/railwayapp/nixpacks:debian-1662422726@sha256:ac27b084ba99f7566  13.0s
 => => resolve ghcr.io/railwayapp/nixpacks:debian-1662422726@sha256:ac27b084ba99f7566c0940a6a6  0.0s
 => => sha256:87f20938588dfe66c7e6550b52c6cf12eeb7e9f9fd6834eadc429c587a96a70c 3.88kB / 3.88kB  0.0s
 => => sha256:1efc276f4ff952c055dea726cfc96ec6a4fdb8b62d9eed816bd2b788f2860a 31.37MB / 31.37MB  1.5s
 => => sha256:7d83fb67ab4cb1e09e5eeba2222486be40482bd46251165c3c114045b94fc2 35.85MB / 35.85MB  1.2s
 => => sha256:b24bfc639ff4abea0e819ed4c237f4a0cfb6eefd023463e69b3f39b8fe76c9 85.48MB / 85.48MB  7.1s
 => => sha256:ac27b084ba99f7566c0940a6a62ac9510bcb811a441428425a89106cc7e335ff 1.05kB / 1.05kB  0.0s
 => => sha256:08dcd442f7c7825125e5a4ac1efedaaaa9b3ec7e9377a649f434a9c793e52079 1.16kB / 1.16kB  0.0s
 => => sha256:7a07c981cf851d5151d80aa71fc75666635a49d434cc489aaa29f146f626bc 24.77kB / 24.77kB  1.6s
 => => extracting sha256:1efc276f4ff952c055dea726cfc96ec6a4fdb8b62d9eed816bd2b788f2860ad7       0.7s
 => => extracting sha256:7d83fb67ab4cb1e09e5eeba2222486be40482bd46251165c3c114045b94fc22c       0.9s
 => => extracting sha256:b24bfc639ff4abea0e819ed4c237f4a0cfb6eefd023463e69b3f39b8fe76c97b       4.6s
 => => extracting sha256:7a07c981cf851d5151d80aa71fc75666635a49d434cc489aaa29f146f626bc4c       0.0s
 => [internal] load build context                                                               0.2s
 => => transferring context: 10.81MB                                                            0.2s
 => [stage-0 2/8] WORKDIR /app/                                                                 0.0s
 => [stage-0 3/8] COPY .nixpacks/setup.nix .nixpacks/setup.nix                                  0.0s
 => [stage-0 4/8] RUN nix-env -if .nixpacks/setup.nix && nix-collect-garbage -d                14.6s
 => [stage-0 5/8] RUN printf '\nPATH=/opt/venv/bin:$PATH' >> /root/.profile                     0.4s
 => [stage-0 6/8] COPY pyproject.toml /app/                                                     0.0s 
 => ERROR [stage-0 7/8] RUN --mount=type=cache,id=JQ3zOliWKQM-/root/cache/pip,target=/root/.ca  9.5s 
------                                                                                               
 > [stage-0 7/8] RUN --mount=type=cache,id=JQ3zOliWKQM-/root/cache/pip,target=/root/.cache/pip python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade build setuptools && pip install .:                                                                                                
#11 4.019 Collecting build                                                                           
#11 4.165   Downloading build-0.8.0-py3-none-any.whl (17 kB)                                         
#11 4.171 Requirement already satisfied: setuptools in /opt/venv/lib/python3.8/site-packages (56.0.0)
#11 4.563 Collecting setuptools
#11 4.586   Downloading setuptools-65.3.0-py3-none-any.whl (1.2 MB)
#11 4.673      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 14.8 MB/s eta 0:00:00
#11 4.753 Collecting tomli>=1.0.0
#11 4.770   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
#11 4.827 Collecting packaging>=19.0
#11 4.845   Downloading packaging-21.3-py3-none-any.whl (40 kB)
#11 4.850      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 KB 11.6 MB/s eta 0:00:00
#11 4.886 Collecting pep517>=0.9.1
#11 4.904   Downloading pep517-0.13.0-py3-none-any.whl (18 kB)
#11 4.989 Collecting pyparsing!=3.0.5,>=2.0.2
#11 5.006   Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
#11 5.012      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 KB 28.9 MB/s eta 0:00:00
#11 5.204 Installing collected packages: tomli, setuptools, pyparsing, pep517, packaging, build
#11 5.219   Attempting uninstall: setuptools
#11 5.220     Found existing installation: setuptools 56.0.0
#11 5.270     Uninstalling setuptools-56.0.0:
#11 5.281       Successfully uninstalled setuptools-56.0.0
#11 5.899 Successfully installed build-0.8.0 packaging-21.3 pep517-0.13.0 pyparsing-3.0.9 setuptools-65.3.0 tomli-2.0.1
#11 6.035 WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
#11 6.035 You should consider upgrading via the '/opt/venv/bin/python -m pip install --upgrade pip' command.
#11 6.577 Processing /app
#11 6.724   Installing build dependencies: started
#11 8.840   Installing build dependencies: finished with status 'done'
#11 8.844   Getting requirements to build wheel: started
#11 9.090   Getting requirements to build wheel: finished with status 'done'
#11 9.092   Preparing metadata (pyproject.toml): started
#11 9.345   Preparing metadata (pyproject.toml): finished with status 'error'
#11 9.353   error: subprocess-exited-with-error
#11 9.353   
#11 9.353   × Preparing metadata (pyproject.toml) did not run successfully.
#11 9.353   │ exit code: 1
#11 9.353   ╰─> [26 lines of output]
#11 9.353       Traceback (most recent call last):
#11 9.353         File "/opt/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#11 9.353           main()
#11 9.353         File "/opt/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#11 9.353           json_out['return_val'] = hook(**hook_input['kwargs'])
#11 9.353         File "/opt/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
#11 9.353           return hook(metadata_directory, config_settings)
#11 9.353         File "/tmp/pip-build-env-a09ea19i/overlay/lib/python3.8/site-packages/pdm/pep517/api.py", line 64, in prepare_metadata_for_build_wheel
#11 9.353           return _prepare_metadata(builder, metadata_directory)
#11 9.353         File "/tmp/pip-build-env-a09ea19i/overlay/lib/python3.8/site-packages/pdm/pep517/api.py", line 48, in _prepare_metadata
#11 9.353           builder._write_metadata_file(f)
#11 9.353         File "/tmp/pip-build-env-a09ea19i/overlay/lib/python3.8/site-packages/pdm/pep517/wheel.py", line 332, in _write_metadata_file
#11 9.353           fp.write(self.format_pkginfo())
#11 9.353         File "/tmp/pip-build-env-a09ea19i/overlay/lib/python3.8/site-packages/pdm/pep517/base.py", line 431, in format_pkginfo
#11 9.353           if meta.long_description:
#11 9.353         File "/tmp/pip-build-env-a09ea19i/overlay/lib/python3.8/site-packages/pdm/pep517/metadata.py", line 41, in __get__
#11 9.353           rv = self.fget(instance, rv)
#11 9.353         File "/tmp/pip-build-env-a09ea19i/overlay/lib/python3.8/site-packages/pdm/pep517/metadata.py", line 90, in _get_readme_content
#11 9.353           return Path(value).read_text(encoding=self.DEFAULT_ENCODING)
#11 9.353         File "/nix/store/xq59cyi96kny4v70flfb3ymrzmymk1k1-python3-3.8.13/lib/python3.8/pathlib.py", line 1236, in read_text
#11 9.353           with self.open(mode='r', encoding=encoding, errors=errors) as f:
#11 9.353         File "/nix/store/xq59cyi96kny4v70flfb3ymrzmymk1k1-python3-3.8.13/lib/python3.8/pathlib.py", line 1222, in open
#11 9.353           return io.open(self, mode, buffering, encoding, errors, newline,
#11 9.353         File "/nix/store/xq59cyi96kny4v70flfb3ymrzmymk1k1-python3-3.8.13/lib/python3.8/pathlib.py", line 1078, in _opener
#11 9.353           return self._accessor.open(self, flags, mode)
#11 9.353       FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
#11 9.353       [end of output]
#11 9.353   
#11 9.353   note: This error originates from a subprocess, and is likely not a problem with pip.
#11 9.355 error: metadata-generation-failed
#11 9.355 
#11 9.355 × Encountered error while generating package metadata.
#11 9.355 ╰─> See above for output.
#11 9.355 
#11 9.355 note: This is an issue with the package mentioned above, not pip.
#11 9.355 hint: See above for details.
#11 9.359 WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
#11 9.359 You should consider upgrading via the '/opt/venv/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/bash -ol pipefail -c python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade build setuptools && pip install .]: exit code: 1
Error: Docker build failed
[rootlesskit:child ] error: command [nixpacks build . --name pyfilesystem-sync] exited: exit status 1
[rootlesskit:parent] error: child exited: exit status 1
```

### To reproduce

No idea. It fails even if I comment the `readme` section in `pyproject.toml`.

### Environment

nixpacks 0.4.1

**Comment by coffee-cup** [comment]
Can you please provide an example repo or share more about the Python project (`pyproject.toml`, file structure, etc.)

**Comment by frafra** [comment]
```bash
cat << EOF > pyproject.toml
[project]
name = "test"
version = "0.0.1"
requires-python = "*"
license = {text = "MIT"}
readme = "README.md"
[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
EOF
touch README.md
rootlesskit nixpacks build . --name test
```
