### ISSUE TITLE
Spring Boot Application Fails to Build Correctly

### ISSUE THREAD

**Issue by Promotos** [railwayapp/nixpacks#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi and thanks a lot for your awesome service.

I try to build and run a simple spring boot 3.0.0 app.
Worked until a couple of hours perfectly on railway.app.
Now I see the following error:

```
#11 3.627
#11 3.627 Welcome to Gradle 7.4.2!
#11 3.627
#11 3.628 Here are the highlights of this release:
#11 3.628  - Aggregated test and JaCoCo reports
#11 3.628  - Marking additional test source directories as tests in IntelliJ
#11 3.628  - Support for Adoptium JDKs in Java toolchains
#11 3.628
#11 3.628 For more details see https://docs.gradle.org/7.4.2/release-notes.html
#11 3.628
#11 3.726 Starting a Gradle Daemon (subsequent builds will be faster)
 
#11 6.926
#11 6.926 FAILURE: Build failed with an exception.
#11 6.926
#11 6.926 * Where:
#11 6.927 Settings file '/app/settings.gradle'
#11 6.927
#11 6.927 * What went wrong:
#11 6.927 Could not compile settings file '/app/settings.gradle'.
#11 6.927 > startup failed:
#11 6.927   General error during conversion: Unsupported class file major version 63
#11 6.927
#11 6.927   java.lang.IllegalArgumentException: Unsupported class file major version 63
#11 6.927   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
#11 6.927   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
#11 6.927   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
#11 6.928   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
#11 6.928   	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
 
#11 6.928   	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
#11 6.928   	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
#11 6.928   	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
#11 6.928   	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
#11 6.928   	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
#11 6.928   	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
#11 6.928   	at org.codehaus.groovy.ast.decompiled.TypeSignatureParser.visitEnd(TypeSignatureParser.java:110)
#11 6.928   	at groovyjarjarasm.asm.signature.SignatureReader.parseType(SignatureReader.java:206)
#11 6.929   	at groovyjarjarasm.asm.signature.SignatureReader.accept(SignatureReader.java:124)
#11 6.929   	at org.codehaus.groovy.ast.decompiled.ClassSignatureParser.parseClassSignature(ClassSignatureParser.java:74)
#11 6.929   	at org.codehaus.groovy.ast.decompiled.ClassSignatureParser.configureClass(ClassSignatureParser.java:32)
#11 6.929   	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitSupers(DecompiledClassNode.java:185)
#11 6.929   	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.isUsingGenerics(DecompiledClassNode.java:86)
```
This looks familiar to the issue in the comments described in [issue-504](https://github.com/railwayapp/nixpacks/issues/504)

### To reproduce

Steps to reproduce

1. Spring-boot application (I guess build with gradle using buildpacks) - as example https://github.com/Promotos/sir-bookmark-backend
2. Try to build on railway.app

### Expected behavior

Expected would be a successful build

### Environment

- spring-boot app 3.0
- JDK 17
- Gradle

```
==============
Using Nixpacks
==============
Inline cache enabled
 
╔═══════════════════════════════ Nixpacks v1.0.0 ══════════════════════════════╗
║ setup      │ jdk, gradle                                                     ║
║──────────────────────────────────────────────────────────────────────────────║
║ build      │ chmod +x gradlew                                                ║
║            │ ./gradlew build -x check                                        ║
║──────────────────────────────────────────────────────────────────────────────║
║ start      │ java $JAVA_OPTS -jar -Dserver.port=$PORT                        ║
║            │ -Dspring.datasource.url=jdbc:postgresql:/xxxx                                    ║
║            │ -Dspring.datasource.username=xxxx║
║            │ -Dspring.datasource.password=xxxx build/libs/sir-  ║
║            │ bookmark-backend-0.0.1-SNAPSHOT.jar                             ║
╚══════════════════════════════════════════════════════════════════════════════╝
```

**Comment by coffee-cup** [comment]
This seems to be failing because the default JDK version on Nixpkgs updated to version 19. I can release an update to default to 17

**Comment by Promotos** [comment]
This would be awesome or if you can give me a hint how I manually specify the JDK would also help.

**Comment by coffee-cup** [comment]
Hey sorry for the delayed response. JDK 17 is now the default. You can also customize which version of the JDK and gradle get installed with environment variables. More information in the docs https://nixpacks.com/docs/providers/java

**Comment by Promotos** [comment]
Perfect, build is successful now. 👍
