### ISSUE TITLE
nixpacks build command not working well

### ISSUE THREAD

**Issue by betoobernal** [railwayapp/nixpacks#940]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi,

I'm trying to use nixpack to generate a docker image. I have followed the steps on the Getting Started page. I would appreciate your help.

### To reproduce

Steps:

Run this:
```bash
sudo nixpacks build ./dir --pkgs openssl --name my-app --build-cmd "lerna run build" --start-cmd "npm run site:start"
``` 

After this I'm having this error:
<img width="904" alt="image" src="https://github.com/railwayapp/nixpacks/assets/4160023/eda6c7a6-a9d6-45e5-8a49-ea1d20f3be4e">

### Environment

MacOs Ventura 13.5
Apple M1
nixpacks 1.12.0

**Comment by betoobernal** [comment]
the goal of this is to get my Dockerfile configured and try to create a mongodb "replica set".
Prisma won't let me make mutations if I don't have it.

This is my deploy logs

```shell
PrismaClientKnownRequestError:
﻿Invalid `prisma.turno.create()` invocation:
﻿Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set. https://pris.ly/d/mongodb-replica-set
﻿at Hr.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6999)
﻿at Hr.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6388)
﻿at Hr.request (/app/node_modules/@prisma/client/runtime/library.js:122:6108)
﻿at l (/app/node_modules/@prisma/client/runtime/library.js:126:10298)
﻿at action (/app/packages/website/build/index.js:181:151)
﻿at Object.callRouteActionRR (/app/node_modules/@remix-run/server-runtime/dist/data.js:35:16)
﻿at callLoaderOrAction (/app/node_modules/@remix-run/router/router.ts:3671:16)
﻿at submit (/app/node_modules/@remix-run/router/router.ts:2829:16)
﻿at queryImpl (/app/node_modules/@remix-run/router/router.ts:2764:22)
﻿at Object.queryRoute (/app/node_modules/@remix-run/router/router.ts:2714:18) {
﻿code: 'P2031',
﻿clientVersion: '5.1.0',
﻿meta: {}
﻿}
``` 

Googling I found this possible configuration to create the replica
```dockerfile
FROM mongo:4.4
RUN echo "rs.initiate();" > /docker-entrypoint-initdb.d/replica-init.js
CMD [ "--replSet", "myrepl" ]
```

**Comment by pinkforest** [comment]
That seems a docker feature in macOS trying to fetch creds from keychain - check your `~/.docker/config.json`
https://github.com/docker/docker-credential-helpers/issues/60#issuecomment-1622539853

**Comment by betoobernal** [comment]
I've disabled the compose v2 (this is because I was trying to find some help on the internet) 
<img width="603" alt="image" src="https://github.com/railwayapp/nixpacks/assets/4160023/38518292-1671-4091-a6f7-fdc7891e3173">
and the message error changed:
```shell
[+] Building 30.3s (10/14)                                                                                          docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                0.0s
 => => transferring dockerfile: 985B                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                   0.0s
 => => transferring context: 2B                                                                                                     0.0s
 => [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1690243402                                                      1.4s
 => [stage-0  1/10] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1690243402@sha256:1a7dc562bf1f13299c20e55f8a72a287cb16dfea072fe4d20d08  0.0s
 => [internal] load build context                                                                                                   9.8s
 => => transferring context: 611.67MB                                                                                               9.6s
 => CACHED [stage-0  2/10] WORKDIR /app/                                                                                            0.0s
 => CACHED [stage-0  3/10] COPY .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix .nixpacks/nixpkgs-293a28df6d7ff3dec  0.0s
 => CACHED [stage-0  4/10] RUN nix-env -if .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix && nix-collect-garbage -  0.0s
 => CACHED [stage-0  5/10] COPY . /app/.                                                                                            0.0s
 => ERROR [stage-0  6/10] RUN --mount=type=cache,id=JhCQwAHZvtY-/root/npm,target=/root/.npm npm ci                                 19.0s
------                                                                                                                                   
 > [stage-0  6/10] RUN --mount=type=cache,id=JhCQwAHZvtY-/root/npm,target=/root/.npm npm ci:                                             
0.564 npm WARN config production Use `--omit=dev` instead.                                                                               
8.529 npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs                                       
9.550 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.                                                 
9.938 npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
18.85 npm ERR! code 1
18.85 npm ERR! path /app/node_modules/@parcel/watcher
18.85 npm ERR! command failed
18.85 npm ERR! command sh -c -- node-gyp-build
18.85 npm ERR! gyp info it worked if it ends with ok
18.85 npm ERR! gyp info using node-gyp@9.4.0
18.85 npm ERR! gyp info using node@16.18.1 | linux | arm64
18.85 npm ERR! gyp ERR! find Python 
18.85 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
18.85 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
18.85 npm ERR! gyp ERR! find Python checking if "python3" can be used
18.85 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
18.85 npm ERR! gyp ERR! find Python checking if "python" can be used
18.85 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
18.85 npm ERR! gyp ERR! find Python 
18.85 npm ERR! gyp ERR! find Python **********************************************************
18.85 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
18.85 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
18.85 npm ERR! gyp ERR! find Python you can try one of the following options:
18.85 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
18.85 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
18.85 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
18.85 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
18.85 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
18.85 npm ERR! gyp ERR! find Python For more information consult the documentation at:
18.85 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
18.85 npm ERR! gyp ERR! find Python **********************************************************
18.85 npm ERR! gyp ERR! find Python 
18.85 npm ERR! gyp ERR! configure error 
18.85 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
18.85 npm ERR! gyp ERR! stack     at PythonFinder.fail (/app/node_modules/node-gyp/lib/find-python.js:330:47)
18.85 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/app/node_modules/node-gyp/lib/find-python.js:159:21)
18.85 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/find-python.js:202:16)
18.85 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/app/node_modules/node-gyp/lib/find-python.js:294:16)
18.85 npm ERR! gyp ERR! stack     at exithandler (node:child_process:410:5)
18.85 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:422:5)
18.85 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
18.85 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
18.85 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:485:16)
18.85 npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
18.85 npm ERR! gyp ERR! System Linux 5.15.49-linuxkit-pr
18.85 npm ERR! gyp ERR! command "/nix/store/sb6haas92rx1j2968j1rfc3hpdak8ilk-nodejs-16.18.1/bin/node" "/app/node_modules/.bin/node-gyp" "rebuild"
18.85 npm ERR! gyp ERR! cwd /app/node_modules/@parcel/watcher
18.85 npm ERR! gyp ERR! node -v v16.18.1
18.85 npm ERR! gyp ERR! node-gyp -v v9.4.0
18.85 npm ERR! gyp ERR! not ok
18.85 
18.85 npm ERR! A complete log of this run can be found in:
18.85 npm ERR!     /root/.npm/_logs/2023-08-03T21_26_32_727Z-debug-0.log
------
Dockerfile:20
--------------------
  18 |     ENV NIXPACKS_PATH /app/node_modules/.bin:$NIXPACKS_PATH
  19 |     COPY . /app/.
  20 | >>> RUN --mount=type=cache,id=JhCQwAHZvtY-/root/npm,target=/root/.npm npm ci
  21 |     
  22 |     # build phase
--------------------
ERROR: failed to solve: process "/bin/bash -ol pipefail -c npm ci" did not complete successfully: exit code: 1
Error: Docker build failed
```
